### ISSUE TITLE
Screenshots in your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [KoroLikesMelon/TheHub#1]
HI!

It looks like you've assembled a really nice set of GUI programs.  I don't know what they looks like though.  It's unusual for Python programs to have a GUI, so images in a readme always grab attention.  

This video will show you how if you're unsure:
https://youtu.be/C4PVKW756fo

**Comment by KoroLikesMelon** [comment]
Thanks! It's nice to see the actual creator of the library show up at a repo. I'll look into it

**Comment by KoroLikesMelon** [comment]
Added the screenshots!

**Comment by PySimpleGUI** [comment]
```
'##::::'##:'########:'########::'##:::'##:
 ##:::: ##: ##.....:: ##.... ##:. ##:'##::
 ##:::: ##: ##::::::: ##:::: ##::. ####:::
 ##:::: ##: ######::: ########::::. ##::::
. ##:: ##:: ##...:::: ##.. ##:::::: ##::::
:. ## ##::: ##::::::: ##::. ##::::: ##::::
::. ###:::: ########: ##:::. ##:::: ##::::
:::...:::::........::..:::::..:::::..:::::
'##::: ##:'####::'######::'########:'####:
 ###:: ##:. ##::'##... ##: ##.....:: ####:
 ####: ##:: ##:: ##:::..:: ##::::::: ####:
 ## ## ##:: ##:: ##::::::: ######:::: ##::
 ##. ####:: ##:: ##::::::: ##...:::::..:::
 ##:. ###:: ##:: ##::: ##: ##:::::::'####:
 ##::. ##:'####:. ######:: ########: ####:
..::::..::....:::......:::........::....::
```

Wow, you made a lot of GUIs!  

You're going about this in a really great way... by building stuff.  I think this is the best way to learn to program.  Not only do you learn and grow, but you also have things that you wanted to build when you're finished.  The result is a useful THING.

I've been a fan of "rainmeter" for many years.  I started to build little PySimpleGUI programs that are like the rainmeter widgets.  All of these are running on secondary monitors.  I have the screen room, the CPU and the RAM to do it, so why not?  It's only 1 button to start them all.

The efficiency improvement from making my own tools has been amazing and until PySimpleGUI wasn't something I had experienced very often.

It's been by making programs that I have learned what parts need more work or could benefit from a new feature.  I wouldn't have added the UserSettings APIs if it weren't for the fact I kept running into the need for "settings" in many of these programs.  I need to be a user, feel the same pain everyone else is feeling, to really get a grasp of the reality that others experience.

Anyway.... Keep making!  You're doing great!

![image](https://user-images.githubusercontent.com/46163555/130463500-8729db54-bc25-4bbf-9de7-81fc24e20598.png)

**Comment by KoroLikesMelon** [comment]
wooow dude thats freaking amazing, i cant wait to do something like that!

**Comment by PySimpleGUI** [comment]
> wooow dude thats freaking amazing, i cant wait to do something like that!

So "do something like that"!  You have already shown you are quite capable of doing it.

Use the Demo Browser and search for "desktop_widget"
![image](https://user-images.githubusercontent.com/46163555/131137054-1b19e8cc-4928-42f5-9f1c-92b998cabd00.png)

I count 22 examples for you to choose from.  Some are newer than others and use recent additions like the Settings APIs

Looking forward to seeing what you make!

**Comment by KoroLikesMelon** [comment]
WOOOAH, dude your so amazing, i also, made an autohotkey key binder application, you can check it out, its in my repos!

**Comment by PySimpleGUI** [comment]
Nah... not amazing.... I like to have fun

![image](https://user-images.githubusercontent.com/46163555/131689179-c05720ed-91f1-4523-a1ab-67cc194e6973.png)

I just like to make stuff.... it's all about having fun for me.  I'm having fun, and it's SO much fun watching other people have fun too!  You're clearly having fun.

Now you've got another of your projects to add a screenshot to!

I made a hotkey binder too.  Here's the repo:
https://github.com/PySimpleGUI/PySimpleHotkey

![PySimpleHotkey](https://user-images.githubusercontent.com/46163555/126043935-5f254bf6-beec-4016-af81-56c7a1261855.gif)

I kinda threw it together.  I wanted to get away from the hotkey manager I've been using and start using this new (new to me) one.  I mostly wanted it to add names of friends Коля and Милка.  I also did it so that I can more easily add my emoji's to issues and text.  

One of them brings up this little floating window:
![image](https://user-images.githubusercontent.com/46163555/131689441-c9615b10-c868-45c3-840f-091e3a7bad3a.png)

USUALLY, I'm choosing this guy:
![image](https://user-images.githubusercontent.com/46163555/131689474-bdc61548-8048-4b95-a6ac-6bed1b46ee3b.png)


I don't do a good job of telling the user what the keys do.  Then again, I'm really the only intended user.  I put up the repo just in case someone wanted to use it as a starting point.

Keep having fun! Keep on building!  You're good at this.  And thank you for the compliment.  I'm no different than you though.

**Comment by KoroLikesMelon** [comment]
Still, it's really impressive, im adding a new project to my repo, so that's why i havent gotten to really configuring the readme's, ill make sure to add it, Thanks!

**Comment by PySimpleGUI** [comment]
I totally understand.  The readme's are among the last things completed.  I'm just having a little fun with ya is all.  You're doing awesome.  You've just started!

**Comment by KoroLikesMelon** [comment]
Thank you man! I really appreciate it!

**Comment by PySimpleGUI** [comment]
Same here! I assure you that I appreciate what you do.  It's SO fun getting to watch other people having fun, experiencing success, being happy about programming, finding passion and fun in the process.  

The list of surprising and thoroughly enjoyable experiences has been long and varied. Watching people fall in love with programming, every day, has been such a thrill and brings back memories that I had almost forgotten it's been so long (a VERY LONG time ago).

I've heard from my friends and other PySimpleGUI users that users are also motivating each other.  So, it's not just me that appreciates what you're doing.
